# Copyright 2026 graph-agents-cli contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Shared Secret provisioning used by ``secrets apply`` and direct-mode ``deploy``.

Only the manifest's allow-listed keys are exported from the env file. ``API_KEY``
is generated when allow-listed, absent from the env file and absent from the
live Secret (one key per environment, generated on first
provisioning); an existing value is kept, because ``kubectl apply`` replaces
``data`` and would otherwise rotate it on every deploy. The Secret is built
with ``kubectl create secret generic --from-env-file --dry-run=client -o yaml``
and piped into ``kubectl apply``; values never appear on a command line.
Values must be single-line: ``--from-env-file`` splits on newlines.
"""

from __future__ import annotations

import base64
import binascii
import io
import json
import os
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from graph_agents_cli._output import Console
from graph_agents_cli.deploy import _kube
from graph_agents_cli.deploy._kube import ConfigError, Target, echo_cmd

GENERATED_KEY = "API_KEY"
# Placeholder shown in a --dry-run manifest for a key that the real run keeps
# from the live Secret or generates (the cluster is not read under --dry-run).
PENDING_PLACEHOLDER = "<kept-or-generated>"


def resolve_env_file(env: str, explicit: str | None) -> Path | None:
    """``--env-file`` when given (must exist), else ``.env.<env>`` then ``.env``."""
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            raise ConfigError(f"Env file not found: {path}")
        return path
    for candidate in (Path(f".env.{env}"), Path(".env")):
        if candidate.is_file():
            return candidate
    return None


def read_env_file(path: Path) -> dict[str, str]:
    from dotenv import dotenv_values

    content = path.read_text(encoding="utf-8")
    return {k: v for k, v in dotenv_values(stream=io.StringIO(content)).items() if v is not None}


def select_allowed(values: dict[str, str], allowed: list[str]) -> dict[str, str]:
    """Keep only allow-listed, non-empty values (never the whole file)."""
    return {k: values[k] for k in allowed if k in values and values[k] != ""}


def generate_api_key() -> str:
    return os.urandom(32).hex()


def _reject_multiline(data: dict[str, str]) -> None:
    """Refuse values ``--from-env-file`` cannot carry (one single-line value per key).

    kubectl splits the env file on newlines: the value would be truncated and
    the remaining lines read as extra keys (a bare ``NAME`` line is even looked
    up in the local environment). Only key names are reported, never values.
    """
    bad = [k for k, v in data.items() if "\n" in v or "\r" in v]
    if bad:
        raise ConfigError(
            "Secret values must be single-line: kubectl --from-env-file splits on newlines, "
            "truncating the value and reading the remaining lines as extra keys. "
            f"Offending key(s): {', '.join(bad)}. Put the value on one line (for example "
            "base64-encode it) or create the Secret with kubectl directly."
        )


@dataclass
class SecretPlan:
    name: str
    target: Target
    data: dict[str, str]
    generated: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)  # allow-listed keys absent from the file
    reused: list[str] = field(default_factory=list)  # kept from the live Secret
    pending: list[str] = field(default_factory=list)  # --dry-run: kept or generated by the real run

    def manifest(self, *, redact: bool = True) -> str:
        body = {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {"name": self.name, "namespace": self.target.namespace},
            "type": "Opaque",
            "stringData": {k: ("<redacted>" if redact else v) for k, v in self.data.items()},
        }
        return yaml.safe_dump(body, sort_keys=False)


def build_plan(
    *,
    name: str,
    target: Target,
    allowed: list[str],
    values: dict[str, str],
    existing: dict[str, str] | None = None,
    dry_run: bool = False,
) -> SecretPlan:
    """Decide the Secret's content: file values > live values (``existing``) > a generated API_KEY.

    Pure: the cluster is read by the caller (``existing_values_for_plan``). Under
    ``dry_run`` an absent ``API_KEY`` is recorded as pending instead of generated,
    since the real run would first look at the live Secret.
    """
    data = select_allowed(values, allowed)
    _reject_multiline(data)
    generated: list[str] = []
    reused: list[str] = []
    pending: list[str] = []
    if GENERATED_KEY in allowed and GENERATED_KEY not in data:
        live = (existing or {}).get(GENERATED_KEY)
        if live:
            data[GENERATED_KEY] = live
            reused.append(GENERATED_KEY)
        elif dry_run:
            data[GENERATED_KEY] = PENDING_PLACEHOLDER
            pending.append(GENERATED_KEY)
        else:
            data[GENERATED_KEY] = generate_api_key()
            generated.append(GENERATED_KEY)
    skipped = [k for k in allowed if k not in data]
    return SecretPlan(
        name=name,
        target=target,
        data=data,
        generated=generated,
        skipped=skipped,
        reused=reused,
        pending=pending,
    )


def existing_values_for_plan(
    name: str,
    target: Target,
    allowed: list[str],
    values: dict[str, str],
    *,
    dry_run: bool,
) -> dict[str, str] | None:
    """Read the live ``API_KEY`` only when the plan would otherwise generate one.

    Nothing is read under ``--dry-run`` (the command never touches a cluster
    then) or when the env file already carries the key.
    """
    if (
        dry_run
        or GENERATED_KEY not in allowed
        or select_allowed(values, allowed).get(GENERATED_KEY)
    ):
        return None
    return existing_secret_values(name, target, [GENERATED_KEY])


def existing_secret_values(name: str, target: Target, keys: list[str]) -> dict[str, str]:
    """Decoded ``data[key]`` (or ``stringData[key]``) of the live Secret for ``keys``.

    ``{}`` when the Secret (or its namespace) does not exist; any other kubectl
    failure is a tool failure (exit 2) rather than a reason to rotate. Values
    are never printed by the callers.
    """
    result = _kube.kubectl(["get", "secret", name, "-o", "json"], target, check=False, quiet=True)
    if result.returncode != 0:
        if "(NotFound)" in (result.stderr or ""):
            return {}
        raise _kube.ToolFailed(
            f"kubectl get secret {name} failed (exit code {result.returncode}) in namespace "
            f"{target.namespace}:\n{(result.stderr or result.stdout or '').strip()}"
        )
    if not (result.stdout or "").strip():
        return {}
    try:
        body = json.loads(result.stdout)
    except json.JSONDecodeError as e:
        raise _kube.ToolFailed(f"kubectl returned invalid JSON: {e}") from e
    data = body.get("data") or {}
    string_data = body.get("stringData") or {}
    found: dict[str, str] = {}
    for key in keys:
        if key in data:
            try:
                found[key] = base64.b64decode(str(data[key])).decode("utf-8")
            except (binascii.Error, UnicodeDecodeError) as e:
                raise ConfigError(
                    f"Secret {name} holds a value for {key} that is not UTF-8 text; "
                    "it cannot be carried through --from-env-file."
                ) from e
        elif key in string_data:
            found[key] = str(string_data[key])
    _reject_multiline(found)
    return found


def _create_cmd(plan: SecretPlan, env_file: str) -> list[str]:
    return _kube.kubectl_args(
        [
            "create",
            "secret",
            "generic",
            plan.name,
            f"--from-env-file={env_file}",
            "--dry-run=client",
            "-o",
            "yaml",
        ],
        plan.target,
    )


def _apply_cmd(plan: SecretPlan) -> list[str]:
    return _kube.kubectl_args(["apply", "-f", "-"], plan.target)


def apply_plan(plan: SecretPlan, *, dry_run: bool = False, console: Console | None = None) -> None:
    """Create or update the Secret. With ``dry_run`` print the pipeline and a redacted manifest."""
    console = console or Console()
    if not plan.data:
        raise ConfigError(
            "No allow-listed secret values to apply. The env file has none of: "
            + ", ".join(plan.skipped)
        )
    if dry_run:
        for key in plan.pending:
            console.print(
                f"  {key} is not in the env file: it would be kept from the live Secret if "
                "present, otherwise generated (nothing is written under --dry-run).",
                style="yellow",
            )
        create = _create_cmd(plan, "TMP_ENV_FILE_WITH_ALLOW_LISTED_KEYS")
        console.print(
            f"  [dry-run] {_kube.pipe_description(create, _apply_cmd(plan))}",
            style="cyan",
            highlight=False,
            markup=False,
        )
        console.print(plan.manifest(redact=True), highlight=False, markup=False)
        return
    for key in plan.reused:
        console.print(f"  {key} kept from the live Secret (not in the env file).", style="dim")
    for key in plan.generated:
        console.print(
            f"  Generated {key} (not in the env file and not in the live Secret). Save it now; "
            f"it is printed once:\n    {key}={plan.data[key]}",
            style="yellow",
            highlight=False,
        )
    fd, tmp_path = tempfile.mkstemp(prefix="graph-agents-cli-secret-", suffix=".env")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            for key, value in plan.data.items():
                handle.write(f"{key}={value}\n")
        os.chmod(tmp_path, 0o600)
        create = _create_cmd(plan, tmp_path)
        apply = _apply_cmd(plan)
        echo_cmd(create, console=console)
        rendered = _kube.run_cmd(create, quiet=True)
        echo_cmd(apply, console=console)
        _kube.run_cmd(apply, input_text=rendered.stdout, quiet=True)
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
    console.print(
        f"  Secret {plan.name} applied in namespace {plan.target.namespace} "
        f"({len(plan.data)} key(s): {', '.join(plan.data)})."
    )
    if plan.skipped:
        console.print(
            f"  Allow-listed keys absent from the env file: {', '.join(plan.skipped)}",
            style="yellow",
        )


def secret_keys_present(
    name: str, target: Target, *, dry_run: bool = False, console: Console | None = None
) -> set[str] | None:
    """Keys present in the Secret, ``None`` when it does not exist (or on dry-run).

    Only kubectl's ``(NotFound)`` reason means "absent" (a missing Secret or
    namespace); a connection, credential or RBAC failure is a tool failure
    (exit 2) with kubectl's own message, never a fabricated "missing" report.
    """
    cmd = _kube.kubectl_args(["get", "secret", name, "-o", "json"], target)
    result = _kube.run_cmd(cmd, check=False, dry_run=dry_run, console=console)
    if dry_run:
        return None
    stderr = (result.stderr or "").strip()
    if result.returncode != 0:
        if "(NotFound)" in stderr:
            return None
        detail = stderr or (result.stdout or "").strip()
        raise _kube.ToolFailed(
            f"Command failed (exit code {result.returncode}): {_kube.format_cmd(cmd)}"
            + (f"\n{detail}" if detail else "")
        )
    if not (result.stdout or "").strip():
        raise _kube.ToolFailed(f"kubectl get secret {name} returned no output")

    try:
        body = json.loads(result.stdout)
    except json.JSONDecodeError as e:
        raise _kube.ToolFailed(f"kubectl returned invalid JSON: {e}") from e
    data = body.get("data") or {}
    string_data = body.get("stringData") or {}
    return set(data) | set(string_data)


def provisioning_procedure(*, project: str, env: str, owner: str, mode: str) -> str:
    """Text printed when deploy refuses to touch Secrets in a CD mode."""
    who = owner or "the platform operator named in secrets.owner"
    return (
        f"In {mode} mode `deploy` never touches Secrets. {who} provisions the Secret "
        f"once per environment from a workstation with cluster access:\n"
        f"    graph-agents-cli secrets apply --env {env} --env-file .env.{env}\n"
        f"  (or `kubectl create secret generic {project}-app ...`). Rotate with `secrets apply` "
        f"followed by `graph-agents-cli deploy --env {env} --restart`."
    )
