# Copyright 2026 Google LLC
# Modifications Copyright 2026 graph-agents-cli contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Upgrade command for upgrading existing projects to newer graph-agents-cli versions."""

import logging
import pathlib

import click

from graph_agents_cli import _api_policy, _tools
from graph_agents_cli._output import Console
from graph_agents_cli._project import (
    MANIFEST_FILENAME,
    NotInProjectError,
    find_project_config,
    find_project_root,
)

from ..utils.backup import make_backup_pre_apply_hook
from ..utils.generation_metadata import metadata_to_cli_args
from ..utils.merge import run_three_way_merge
from ..utils.upgrade import update_cli_metadata
from ..utils.version import PACKAGE_NAME, get_current_version

console = Console()


def _display_version_header(old_version: str, new_version: str) -> None:
    """Display the upgrade version header."""
    console.print()
    console.print(f"[bold blue]📦 Upgrading {old_version} → {new_version}[/bold blue]")
    console.print()


@click.command()
@click.argument(
    "project_path",
    type=click.Path(exists=True, path_type=pathlib.Path),
    default=".",
    required=False,
)
@click.option(
    "--dry-run",
    "--dryrun",
    is_flag=True,
    help="Preview changes without applying them",
)
@click.option(
    "--auto-approve",
    "--yes",
    "-y",
    is_flag=True,
    help="Auto-apply non-conflicting changes without prompts",
)
@click.option(
    "--interactive",
    "-i",
    is_flag=True,
    default=False,
    help="Enable interactive prompts for human use",
)
@click.option(
    "--baseline",
    type=click.Choice(["authentic", "current"]),
    default="authentic",
    show_default=True,
    help=(
        "Which templates render the old snapshot: 'authentic' runs the exact prior "
        "CLI version through uvx and stops if it cannot; 'current' is an explicit "
        "opt-in to compare against the current templates instead"
    ),
)
@click.option(
    "--debug",
    is_flag=True,
    help="Enable debug logging",
)
def upgrade(
    project_path: pathlib.Path,
    dry_run: bool,
    auto_approve: bool,
    interactive: bool,
    baseline: str,
    debug: bool,
) -> None:
    """Upgrade project to a newer graph-agents-cli version.

    Applies a 3-way merge between the old template, the new template, and your
    project: unmodified files are auto-updated, your customizations are preserved,
    and conflicts are surfaced for manual resolution (with --interactive) or kept as-is.

    The old template is regenerated by the exact CLI version that scaffolded the
    project. If that version cannot be fetched and run, the upgrade stops with
    no changes; pass --baseline current to compare against the current
    templates instead (the summary is labelled accordingly).
    """
    if debug:
        logging.basicConfig(level=logging.DEBUG, force=True)
        console.print("[dim]Debug mode enabled[/dim]")

    project_dir = project_path.resolve()
    project_root_dir = find_project_root(project_dir)
    if project_root_dir is not None:
        project_dir = project_root_dir
        console.print(f"[dim]Resolved project root to: {project_dir}[/dim]")

    metadata = find_project_config(project_dir)
    if not metadata:
        # A configuration error (exit 3), like every other command outside a project.
        raise NotInProjectError(
            f"No {MANIFEST_FILENAME} found in {project_dir} or its parents.\n"
            "  Run scaffold upgrade from a project graph-agents-cli created, or pass its path."
        )

    # The retired product API policy must be migrated first: an upgrade would
    # otherwise re-render the project without it.
    _api_policy.ensure_no_legacy_api_policy(project_dir)

    language = metadata.language

    old_version = metadata.cli_version
    if not old_version:
        console.print("[bold red]Error:[/bold red] No cli_version found in project metadata.")
        console.print(
            "The project metadata is missing the version. "
            f"Please ensure {MANIFEST_FILENAME} has cli_version set."
        )
        raise SystemExit(1)

    new_version = get_current_version()

    if old_version == new_version:
        console.print(f"[bold green]✅[/bold green] Project is already at version {new_version}")
        return

    if baseline == "authentic":
        # Checked up front: without uvx the authentic baseline cannot be built
        # and the merge would stop anyway, after generating nothing.
        try:
            _tools.require_tool("uvx")
        except _tools.ToolNotFoundError as e:
            console.print(f"[bold red]Error:[/bold red] {e.message}")
            console.print(
                f"[dim]The authentic {old_version} baseline needs uvx. Install uv, or re-run "
                "with --baseline current to compare against the current templates.[/dim]"
            )
            raise SystemExit(1) from e
    else:
        logging.warning(
            "--baseline current: the %s snapshot will be rendered with the current "
            "templates, not by %s@%s.",
            old_version,
            PACKAGE_NAME,
            old_version,
        )
        console.print(
            "[yellow]⚠️  --baseline current: comparing against the current templates instead "
            f"of {PACKAGE_NAME}@{old_version}. Deletions and updates between the two versions "
            "may be misclassified; review the result.[/yellow]"
        )

    _display_version_header(old_version, new_version)

    project_name = metadata.project_name or project_dir.name
    agent_directory = metadata.agent_directory or "app"
    # The old snapshot is rendered by the CLI that scaffolded the project, which
    # may spell some values differently; the new one by this CLI.
    old_args = metadata_to_cli_args(
        metadata, cli_version=old_version if baseline == "authentic" else None
    )
    cli_args = metadata_to_cli_args(metadata)

    backup_hook = make_backup_pre_apply_hook(
        console=console,
        auto_approve=auto_approve,
        interactive=interactive,
    )

    # Post-apply: stamp the new version into the manifest
    def _update_version(proj_dir: pathlib.Path, lang: str) -> None:
        update_cli_metadata(proj_dir, {}, cli_version=new_version)

    success = run_three_way_merge(
        project_dir=project_dir,
        project_name=project_name,
        agent_directory=agent_directory,
        language=language,
        old_args=old_args,
        new_args=cli_args,
        old_version=old_version,
        baseline=baseline,  # type: ignore[arg-type]
        auto_approve=auto_approve,
        dry_run=dry_run,
        interactive=interactive,
        operation_label="upgrade",
        pre_apply_hook=backup_hook,
        post_apply_hook=_update_version,
    )

    if not success:
        console.print(
            f"[bold red]Error:[/bold red] Could not build the {PACKAGE_NAME}@{old_version} "
            "baseline (the version that scaffolded this project), so the upgrade diff "
            "cannot be computed authentically."
        )
        console.print(
            "[dim]Your project was not modified. Check your network/proxy and retry, or "
            "re-run with --baseline current to compare against the current templates "
            "(the result is labelled as such).[/dim]"
        )
        raise SystemExit(1)
